### ISSUE TITLE
Error content not displayed

### ISSUE THREAD

**Issue by ghost** [middlewares/error-handler#1]
Hi,

I set this middleware at the top of the stack, The errors and exception are well intercepted (I saw them into my Logger) but my response content is not displayed.

I use the following code:
`( new Middlewares\ErrorHandler( 'App::errorHandler' ) )->catchExceptions( true ),`

And my handler is like
```
static public function errorHandler( ServerRequestInterface $request ) {
    //Get the error info using the "error" attribute
    $error = $request->getAttribute( 'error' );
    $response = ( new Response() )->withStatus( $error[ 'status_code' ] );

    switch ( $error['status_code'] ) {
      case 404:
        App::$view->setView( 'errorNotFound' );
        $output = App::$view->__invoke();
        $response->getBody()->write( $output );

      case 503:
        App::$view->setView( 'maintenance' );
        $output = App::$view->__invoke();
        $response->getBody()->write( $output );

      default:
        App::$logger->debug( $error[ 'exception' ]->getMessage() );
        App::$view->setView( 'errorServer' );
        $output = App::$view->__invoke();
        $response->getBody()->write( $output );
    }

    return $response;
  }
```

What am I doing wrong ?

**Comment by ghost** [comment]
Just for information I'm using middleman as dispatcher. And I'm facing the same issue using the dispatcher from Middlewares\Utils

**Comment by oscarotero** [comment]
Middleman is using an old version of the PSR-15 interface (`0.2` instead the current `0.4`). I recommend using the dispatcher from Middleware\Utils.
Anyway, I suspect this is a bug in your code:

* You should add a `break` after each case in the switch
* If you don't see the response, are you sure the body has content?
* Is being the response emitted?

**Comment by ghost** [comment]
Hi,

I used the dispatcher from Middleware\Utils but same result. I've already added a break after each case (not in the version I copied / pasted here sorry)
If I put a var_dump( $response->getBody() ); exit( 1); the page is well displayed.

Into my app I just do:
$dispatcher = new Middlewares\Utils\Dispatcher( $middlewares );
$response = App::$dispatcher->dispatch( ServerRequestFactory::fromGlobals() );

Do I have to do anything else to emit the response ? I thought the dispatcher handled that.

**Comment by oscarotero** [comment]
Nop, the dispatcher returns the response but does not output the content to the browser. If you're using [diactoros](https://github.com/zendframework/zend-diactoros), it provides some emitters, depending of your needs. For example:

```php
$emitter = new Zend\Diactoros\Response\SapiEmitter();
$emitter->emit($response);
```

**Comment by ghost** [comment]
Thank you for all  your job and for your answer.
