### ISSUE TITLE
question : usefullness of the StreamFactoryInterface parameter in the constructor ?

### ISSUE THREAD

**Issue by ncou** [middlewares/error-handler#6]
Hi,

Why are you using as parameter a streamfactory ? the response factory should already initialise a blank and writable stream.
So instead of creating a new body and inject it in the response, you can simply use the one in the new response.

https://github.com/middlewares/error-handler/blob/master/src/ErrorHandler.php#L78

you can simply do something like :

```php
$response->getBody()->write($formatter->format($e));
```

Am i missing something ?

**Comment by oscarotero** [comment]
I'm agree with you. In fact, there's a conversation about this topic: https://github.com/middlewares/error-handler/pull/5/files#r227117082

**Comment by ncou** [comment]
Thank you, i didn't see this PR. I have added my opinion in this topic.
